apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubby-cloudserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubby-cloudserver
  serviceName: kubby-cloudserver
  template:
    metadata:
      labels:
        app: kubby-cloudserver
    spec:
      containers:
        - name: cloudserver
          image: ghcr.io/corang/cloudserver:8.8.17
          ports:
            - containerPort: 8000
              protocol: TCP
              name: s3
          volumeMounts:
            - name: app-data
              mountPath: /usr/src/app/localData
            - name: app-metadata
              mountPath: /usr/src/app/localMetadata
            - name: config
              mountPath: /usr/src/app/config.json
              subPath: config.json
            - name: config
              mountPath: /usr/src/app/locationConfig.json
              subPath: locationConfig.json
          env:
            - name: S3DATA
              value: "file"
            - name: S3BACKEND
              value: "file"
            - name: S3METADATA
              value: "file"
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "1"
            - name: SCALITY_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: kubby-cloudserver
            - name: SCALITY_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: kubby-cloudserver
      volumes:
        - name: config
          configMap:
            name: kubby-cloudserver-config
  volumeClaimTemplates:
    - metadata:
        name: app-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: app-metadata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
