{{- range $bucket := .Values.buckets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kubby-create-{{ $bucket }}
  labels:
    {{- include "kubby.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubby.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: kubby-create-bucket
          image: amazon/aws-cli:latest
          args:
            - "--endpoint-url=http://{{ include "kubby.fullname" $ }}:{{ $.Values.service.port }}"
            - "s3"
            - "mb"
            - "s3://{{ $bucket }}"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kubby-credentials
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kubby-credentials
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
      restartPolicy: Never
---
{{- end }}
