apiVersion: v1
kind: ConfigMap
metadata:
  name: kubby-cloudserver-config
# Based on number of replicas at .Values.mongodb.replicas, create the replicaSetHosts string
{{- $replicaSetHosts := "" }}
{{- range $i, $e := until (.Values.mongodb.replicaCount | int) }}
{{- $replicaSetHosts = printf "kubby-mongodb-%d.kubby-mongodb-headless:27017,%s" $e $replicaSetHosts }}
{{- end }}
{{- $replicaSetHosts = trimSuffix "," $replicaSetHosts }}
data:
  config.json: |
    {
        "port": 8000,
        "listenOn": [],
        "metricsPort": 8002,
        "metricsListenOn": [],
        "replicationGroupId": "RG001",
        "restEndpoints": {
            "localhost": "us-east-1",
            "127.0.0.1": "us-east-1",
            "{{ include "kubby.fullname" . }}": "us-east-1",
            "{{ include "kubby.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local": "us-east-1",
            "{{ include "kubby.fullname" . }}-cloudserver-frontend": "us-east-1"
        },
        "websiteEndpoints": [],
        "replicationEndpoints": [{
            "site": "zenko",
            "servers": ["127.0.0.1:8000"],
            "default": true
        }],
        "backbeat": {
            "host": "localhost",
            "port": 8900
        },
        "workflowEngineOperator": {
            "host": "localhost",
            "port": 3001
        },
        "cdmi": {
            "host": "localhost",
            "port": 81,
            "path": "/dewpoint",
            "readonly": true
        },
        "bucketd": {
            "bootstrap": ["localhost:9000"]
        },
        "vaultd": {
            "host": "localhost",
            "port": 8500
        },
        "clusters": 1,
        "log": {
            "logLevel": "info",
            "dumpLevel": "error"
        },
        "healthChecks": {
            "allowFrom": ["0.0.0.0/0"]
        },
        "metadataClient": {
            "host": "localhost",
            "port": 9990
        },
        "dataClient": {
            {{- if .Values.ha }}
            "host": "{{ include "kubby.fullname" . }}-cloudserver-data",
            {{- else }}
            "host": "localhost",
            {{- end }}
            "port": 9991
        },
        "pfsClient": {
            "host": "localhost",
            "port": 9992
        },
        "metadataDaemon": {
            "bindAddress": "::",
            "port": 9990
        },
        "dataDaemon": {
            "bindAddress": "::",
            "port": 9991
        },
        "pfsDaemon": {
            "bindAddress": "localhost",
            "port": 9992
        },
        "recordLog": {
            "enabled": true,
            "recordLogName": "s3-recordlog"
        },
        {{- if .Values.ha.mongodb.internal }}
        "mongodb": {
            "replicaSetHosts": "{{ $replicaSetHosts }}",
            "writeConcern": "majority",
            "replicaSet": "rs0",
            "readPreference": "primary",
            "database": "metadata"
        },
        {{- else -}}
        "mongodb": {
            "replicaSetHosts": "{{ .Values.ha.mongodb.external.replicaSetHosts }}",
            "writeConcern": "{{ .Values.ha.mongodb.external.writeConcern }}",
            "replicaSet": "{{ .Values.ha.mongodb.external.replicaSet }}",
            "readPreference": "{{ .Values.ha.mongodb.external.readPreference }}",
            "database": "{{ .Values.ha.mongodb.external.database }}"
        },
        {{- end }}
        "externalBackends": {},
        "requests": {
            "viaProxy": false,
            "trustedProxyCIDRs": [],
            "extractClientIPFromHeader": ""
        },
        "bucketNotificationDestinations": [
            {
                "resource": "target1",
                "type": "dummy",
                "host": "localhost:6000"
            }
        ]
    }
  locationConfig.json: |
    {
        {{- range $region := .Values.extraRegions }}
        "{{ $region }}": {
            "type": "file",
            "objectId": "{{ $region }}",
            "legacyAwsBehavior": false,
            "details": {}
        },
        {{- end }}
        "us-east-1": {
            "type": "file",
            "objectId": "us-east-1",
            "legacyAwsBehavior": true,
            "details": {}
        },
        "us-east-2": {
            "type": "file",
            "objectId": "us-east-2",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "us-gov-east-1": {
            "type": "file",
            "objectId": "us-gov-east-1",
            "legacyAwsBehavior": true,
            "details": {}
        },
        "us-west-1": {
            "type": "file",
            "objectId": "us-west-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "us-west-2": {
            "type": "file",
            "objectId": "us-west-2",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "us-gov-west-1": {
            "type": "file",
            "objectId": "us-gov-west-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ca-central-1": {
            "type": "file",
            "objectId": "ca-central-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "cn-north-1": {
            "type": "file",
            "objectId": "cn-north-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ap-south-1": {
            "type": "file",
            "objectId": "ap-south-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ap-northeast-1": {
            "type": "file",
            "objectId": "ap-northeast-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ap-northeast-2": {
            "type": "file",
            "objectId": "ap-northeast-2",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ap-southeast-1": {
            "type": "file",
            "objectId": "ap-southeast-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "ap-southeast-2": {
            "type": "file",
            "objectId": "ap-southeast-2",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "eu-central-1": {
            "type": "file",
            "objectId": "eu-central-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "eu-west-1": {
            "type": "file",
            "objectId": "eu-west-1",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "eu-west-2": {
            "type": "file",
            "objectId": "eu-west-2",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "EU": {
            "type": "file",
            "objectId": "EU",
            "legacyAwsBehavior": false,
            "details": {}
        },
        "sa-east-1": {
            "type": "file",
            "objectId": "sa-east-1",
            "legacyAwsBehavior": false,
            "details": {}
        }
    }
