apiVersion: v1
kind: Secret
metadata:
  name: kubby-credentials
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "kubby-credentials" }}
data:
  {{- if $previous }}
  accessKey: {{ $previous.data.accessKey }}
  {{- else if .Values.accessKey }}
  accessKey: {{ .Values.accessKey | b64enc | quote }}
  {{- else }}
  accessKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if $previous }}
  secretKey: {{ $previous.data.secretKey }}
  {{- else if .Values.secretKey }}
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  {{- else }}
  secretKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
