apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kubby.fullname" . }}
  labels:
    {{- include "kubby.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubby.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kubby.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubby.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubby.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: s3
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: metrics
          readinessProbe:
            httpGet:
              path: /live
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-data
              mountPath: /usr/src/app/localData
            - name: app-metadata
              mountPath: /usr/src/app/localMetadata
            - name: config
              mountPath: /usr/src/app/config.json
              subPath: config.json
            - name: config
              mountPath: /usr/src/app/locationConfig.json
              subPath: locationConfig.json
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: S3DATA
              value: "file"
            - name: S3BACKEND
              value: "file"
            - name: S3METADATA
              value: "file"
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "1"
            - name: SCALITY_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: kubby-credentials
            - name: SCALITY_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: kubby-credentials
      
      volumes:
        - name: config
          configMap:
            name: kubby-cloudserver-config
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: app-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: app-metadata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
