{{ if .Values.ha.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubby.fullname" . -}}-cloudserver-data
  labels:
    {{- include "kubby.labels-data" . | nindent 4 }}
spec:
  {{- with .Values.ha.data.storage.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ha.data.storage.size }}
  {{ if .Values.ha.data.storage.storageClass }}
  storageClassName: {{ .Values.ha.data.storage.storageClass }}
  {{- end }}
{{- end }}
