{{ if .Values.ha.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubby.fullname" . }}-cloudserver-data
  labels:
    {{- include "kubby.labels-data" . | nindent 4 }}
spec:
  type: {{ .Values.ha.data.service.type }}
  ports:
    - port: {{ .Values.ha.data.service.port }}
      targetPort: data
      protocol: TCP
      name: data
  selector:
    {{- include "kubby.selectorLabels-data" . | nindent 4 }}
{{ end -}}
