{{ if .Values.ha.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubby.fullname" . }}-cloudserver-frontend
  labels:
    {{- include "kubby.labels-frontend" . | nindent 4 }}
spec:
  type: {{ .Values.ha.frontend.service.type }}
  ports:
    - port: {{ .Values.ha.frontend.service.port }}
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    {{- include "kubby.selectorLabels-frontend" . | nindent 4 }}
{{ end -}}
