image:
  repository: ghcr.io/corang/cloudserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mongodb:
  architecture: replicaset
  useStatefulSet: true
  replicaCount: 3
  auth:
    usernames: [kubby]
    passwords: [kubby]
    databases: [metadata]

ha:
  enabled: true

  mongodb: 
    internal: true
    external:
      replicaSetHosts: ""
      writeConcern: "majority"
      replicaSet: "rs0"
      readPreference: "primary"
      database: "metadata2"

      username: ""
      usernameFromSecret:
        usernameKey: ""
        usernameSecret: ""

      password: ""
      passwordFromSecret:
        passwordKey: ""
        passwordSecret: ""

  replicaCount: 3

  frontend:
    # TODO: Add autoscaling
    autoscaling:
      enabled: false
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80`

    podAnnotations: {}
    podLabels: {}

    podSecurityContext: {}
    securityContext: {}

    service:
      type: ClusterIP
      port: 80

    resources: {}

    livenessProbe:
      httpGet:
        path: /live
        port: metrics

    readinessProbe:
      httpGet:
        path: /live
        port: metrics

    volumes: []

    volumeMounts: []

    nodeSelector: {}

    tolerations: []

    affinity: {}

  data:
    # TODO: Add autoscaling
    autoscaling:
      enabled: false
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80`

    podAnnotations: {}
    podLabels: {}

    podSecurityContext: {}
    securityContext: {}

    storage:
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    service:
      type: ClusterIP
      port: 9991

    resources: {}

    livenessProbe:
      tcpSocket:
        port: data

    readinessProbe:
      tcpSocket:
        port: data

    volumes: []

    volumeMounts: []

    nodeSelector: {}

    tolerations: []

    affinity: {}

# List of buckets to create on startup
buckets: ["test"]

# List of extra regions to allow access to
extraRegions: []

# Specify your accessKey and secretKey
# Leave blank to allow helm to generate secure values for you
# Minimum of 16 characters
accessKey: ""
secretKey: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /live
    port: metrics
readinessProbe:
  httpGet:
    path: /live
    port: metrics

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
