apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubby-cloudserver-s3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubby-cloudserver-s3
  template:
    metadata:
      labels:
        app: kubby-cloudserver-s3
    spec:
      containers:
        - name: cloudserver
          image: ghcr.io/corang/cloudserver:8.8.25
          args:
            - "yarn"
            - "start_s3server"
          ports:
            - containerPort: 8000
              protocol: TCP
              name: s3
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/config.json
              subPath: config.json
            - name: config
              mountPath: /usr/src/app/locationConfig.json
              subPath: locationConfig.json
          env:
            - name: MONGODB_AUTH_USERNAME
              value: "root"
            - name: MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: mongo-mongodb
            - name: S3DATA
              value: "file"
            - name: S3BACKEND
              value: "file"
            - name: S3METADATA
              value: "mongodb"
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "1"
            - name: SCALITY_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: kubby-cloudserver
            - name: SCALITY_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: kubby-cloudserver
      volumes:
        - name: config
          configMap:
            name: kubby-cloudserver-config
