name: Release chart

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pages Release
        id: pages
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: deploy
          skip_existing: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push helm chart to ghcr
        if: ${{ steps.pages.outputs.changed_charts != '' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io
          helm package deploy/helm/
          helm push ./kubby-*.tgz oci://ghcr.io/corang/kubby-chart
